// <auto-generated />
using Clubs.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clubs.Migrations
{
    [DbContext(typeof(ClubsContext))]
    partial class ClubsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Clubs.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("League")
                        .HasMaxLength(30)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            League = 3,
                            Name = "PSG"
                        },
                        new
                        {
                            Id = 2,
                            League = 2,
                            Name = "Atletico Madrid"
                        },
                        new
                        {
                            Id = 3,
                            League = 2,
                            Name = "Real Madrid"
                        });
                });

            modelBuilder.Entity("Clubs.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            FullName = "Lionel Messi",
                            Nationality = "Argentina",
                            Position = 3
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 2,
                            FullName = "Cristiano Ronaldo",
                            Nationality = "Portugal",
                            Position = 3
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 3,
                            FullName = "Luka Modric",
                            Nationality = "Croacia",
                            Position = 2
                        });
                });

            modelBuilder.Entity("Clubs.Entities.Player", b =>
                {
                    b.HasOne("Clubs.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Clubs.Entities.Club", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
